// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApnhq2qd55HHllTTAb0smsVNGROSInsDk',
    appId: '1:258424839924:web:b4d6009ad5d5ab3e2dc8a1',
    messagingSenderId: '258424839924',
    projectId: 'neon-node-87e6a',
    authDomain: 'neon-node-87e6a.firebaseapp.com',
    databaseURL: 'https://neon-node-87e6a-default-rtdb.firebaseio.com',
    storageBucket: 'neon-node-87e6a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMLVKfW2NHFT4jwRAHMa-UA1hlbI2WEEA',
    appId: '1:258424839924:android:8227504c6214cd782dc8a1',
    messagingSenderId: '258424839924',
    projectId: 'neon-node-87e6a',
    databaseURL: 'https://neon-node-87e6a-default-rtdb.firebaseio.com',
    storageBucket: 'neon-node-87e6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeBJ_qlIaSarZw6AJfLz_tnyOq3NNS5og',
    appId: '1:258424839924:ios:dc19c33982faa1f02dc8a1',
    messagingSenderId: '258424839924',
    projectId: 'neon-node-87e6a',
    databaseURL: 'https://neon-node-87e6a-default-rtdb.firebaseio.com',
    storageBucket: 'neon-node-87e6a.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

}